Obromios bug fixes
hideakitai/MPU9250 pull request #50
Opened 2021-05-12 01:58 UTC by obromios

This is similar to PR #49 but with experimental features and calibration enhancements removed.

## Fixes for issue #33 (Intermittent errors in reading mag data)
- Add a while loop in read_mag() to check ST1 is set correctly
- Added a time out for the while loop
- Added a setting, mpu.set_mag_time_out to control length of timeout

## Fix for issue #34 (Gyro readings noisy)
- Inverted application of setting.gyro_fchoice in initMPU9250()

## Fix for issue #39 (initMPU9250() is not initializing the accelerometer)
- Added a reset at beginning of initMPU9250()

## Fix for issue #45 (Consistent use of fuse values)
- In collect_mag_data(), used mag_bias_factory[i] as a multiplicative factor in calculation of scale[i]

## Fix for issues #46, #48, #42 and #30.

These issues are 

- What is the correct way to transform the raw readings for the quaternion update (#46)
- Using setMagneticDeclination does not work properly (#48)
- Yaw offset problem (#42)
- Wrong Linear Acceleration readings (#30)
- Root cause of all these issues was related to the choice of coordinate systems.
- The fix was to provide a setting to switch between coordinate systems.
- At present, two options are provided, NED and NWU.  NWU is only partially supported (see below)

## Partial support for NWU coordinate systems
- The commit on January 5 (455a9efd109cb5c9f0bc96710979cb451ef2fae9), made a change to the coordinate system being fed into the quaternion filter (see issue #46).  Prior to this, the coordinate system was the same used by Kris Winer, NED. After this change there was a new coordinate system, which until clarification is being called NWU.
- This was a breaking change that caused a number of other issues (#48, #42, and #30). There maybe other problems caused by the breaking change that have yet to be detected.   Accordingly, a setting has been introduced that allows the coordinate system to be set back to NED.  This fixes these issues.
- There is also a settings option to change the coordinate system to NWU, but using this option will cause the issues in #48, #42, and #30 to reappear.  As well, there is an extremely long settling time for rotations in the horizontal plane.  It may possible to rectify each issue (and other possible undetected issues) by making changes specific the NWU coordinate system.
- Given using the NWU system currently causes breaking changes, it is recommended that the default coordinate system be reverted to NED, until the NWU coordinate option is fully implemented. If no further work is to be done on the NWU coordinate system, it is recommended that it is removed as an option.

2021-05-21 10:59 UTC, hideakitai requested changes
Sorry for the late reply. I've checked your code and there are many unnecessary changes so please revert them.

About #33, your suggestion is not correct and I've made changes in 2a151e0eec30f26838af99829f634d260e4b6e21. 

About fixes for #34 and #39 are OK but I can't merge them because this pull request is not small to merge right now... 

I've made example commits about #34 and #39 4a58e270562dc4eab219e81ad0d510a0f4725afb and ebe2a8830baafddacfb1980fba38fa8f4fa1ad6c, so if you are ok, I can merge them by myself. If you can create small pull requests each for them, I will wait for it.

The rest of the pull requests will be reviewed next week... Thank you for your contribution!

2021-05-21 10:59 UTC, hideakitai commented on MPU9250.h
> +        c = c | (uint8_t(setting.gyro_fs_sel) << 3);          // Set full scale range for the gyro
No need to change these lines

2021-05-21 10:59 UTC, hideakitai commented on MPU9250.h
> +    bool b_verbose{false};
No need to delete spaces

2021-05-21 10:59 UTC, hideakitai commented on MPU9250.h
> +    int mag_time_out {1000};  // Timeout for read_mag in ms
No need to add timeout. Please see 2a151e0eec30f26838af99829f634d260e4b6e21

2021-05-21 10:59 UTC, hideakitai commented on MPU9250.h
> +
No need to add this function. Please see 2a151e0eec30f26838af99829f634d260e4b6e21

2021-05-21 10:59 UTC, hideakitai commented on MPU9250.h
> +
No need to add

2021-05-21 10:59 UTC, hideakitai commented on MPU9250.h
> +        c = c | (uint8_t(~setting.gyro_fchoice) & 0x03);       // Set Fchoice for the gyro by loading complement of Fchoice into Fchoice_b bits.
Ok, please see 4a58e270562dc4eab219e81ad0d510a0f4725afb

2021-05-21 10:59 UTC, hideakitai commented on MPU9250.h
> +
No need to add line

2021-05-21 10:59 UTC, hideakitai commented on MPU9250.h
> +        if ((!ST1 & 0x01) && b_verbose) Serial.println("Warning - read_mag() timed out");
No need to add these lines. Please see 2a151e0eec30f26838af99829f634d260e4b6e21

2021-05-21 10:59 UTC, hideakitai commented on MPU9250.h
> +
No need to add these lines

2021-05-21 10:59 UTC, hideakitai commented on MPU9250.h
> +        delay(100);
Ok, please see ebe2a8830baafddacfb1980fba38fa8f4fa1ad6c

2021-05-24 05:05 UTC, hideakitai commented
@obromios I've also fixed coordinate issues in 23fb7d961164543e55c2815e0aad5f378aa672a3 .

I've selected to revert calculation to NED and just flip the direction to get euler angles. Maybe a series of commits fixes all issues you have listed, and if you agree and can confirm if it works, I will merge the branch. How do you think about it?

2021-05-28 01:17 UTC, obromios commented
@hideakitai, I have checked and the NED angles appears to be correct.  I think all the other changes appear to work. It is looking good.

Chris

2021-05-28 01:37 UTC, hideakitai commented
@obromios If you can agree with my changes, can I merge the branch above into the main branch instead of this pull request?

2021-05-28 01:52 UTC, obromios commented
I assume by the branch above you mean https://github.com/hideakitai/MPU9250/tree/bugfix_obromious.  I agree  with merging that branch.

2021-05-28 02:22 UTC, hideakitai commented
@obromios Thank you, please open the new pull request if you have additional suggestions. Thank you so much for your huge contribution!

2021-05-28 02:23 UTC, hideakitai commented
Fixed in v0.4.3

2021-05-28 02:23 UTC, closed without merging